### ISSUE TITLE
enable --nolock in snakemake workflow, or --unlock on command line

### ISSUE THREAD

**Issue by taylorreiter** [marbl/MetaCompass#11]
Encountered lock error during STAMPS MBL 2019 tutorial. Can you disable locking, or enable `--unlock` so we can unlock without deleting `.snakemake`?

@ryanpeek @astrobiomike

```
MissingInputException in line 42 of /opt/MetaCompass/snakemake/metacompass.iter0.paired.py:
Missing input files for rule merge_reads:
SRR606249_subset10_1.fqSRR606249_subset10_2.fq
unlocking
removed all locks
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/output
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal ora power loss. It can be removed with the --unlock argument.
```

**Comment by vcepeda** [comment]
Use the --clobber option.

**Comment by taylorreiter** [comment]
that did not unlock the snakefile. I had to delete the `.snakemake` directory.

**Comment by vcepeda** [comment]
I haven't encountered that problem. --clobber always works for me. If it doesn't work you can delete all the content inside the --output and use the --clobber option. If that doesn't work, please specify the commands you are trying.

**Comment by taylorreiter** [comment]
This was on a learners machine during a STAMPS MBL 2019 tutorial, I don't have access to the exact command. However, `--clobber` did not work, and there was no way to unlock the snakefile. Deleting the `.snakemake` folder worked. Feel free to close the issue as I cannot reproduce the learners compute environment now.
