### ISSUE TITLE
Snakemake error while running MetaCompass (unrecognized arguments: -T)

### ISSUE THREAD

**Issue by ciemanek** [marbl/MetaCompass#14]
When I try to run MetaCompass on my single-end reads, I get the following error:

`snakemake: error: unrecognized arguments: -T`

I go for my own reference genome and the command I use to run MetaCompass is as follows:

`./MetaCompass/go_metacompass.py -U sample.fastq -r reference.fasta -o workdir/assembly/metacompass`

**Comment by vcepeda** [comment]
where you able to run the readme examples successfully?

**Comment by ciemanek** [comment]
It is the same issue with the examples. i am using snakemake 5.10.0. I tried to find the -T parameter in snakemake documentation and the closest I found was -t (-touch) - was meant to be the one?

**Comment by vcepeda** [comment]
the -T parameter print timestamps. I added the new script "go_metacompass2.py" that doesn't use that option for testing. Please let me know if it works for you.

**Comment by ciemanek** [comment]
thank you! it resolved the -T parameter issue, however I get the error abut `buildcontig` being missing:

`bash: /root/workspace/bioinfo-tests/feat2seq/MetaCompass/bin/buildcontig: No such file or directory`

**Comment by vcepeda** [comment]
Did you get any error while running the install.sh script?
