### ISSUE TITLE
Using MetaCompass with GTDB instead of refseq

### ISSUE THREAD

**Issue by chassenr** [marbl/MetaCompass#15]
Hi @vcepeda,
thanks for this very interesting new tool!
I am about to install MetaCompass for the first time, and I have a question about the reference database (refseq), which is downloaded by default in the install.sh script. Is it possible to supply a different reference database, e.g. gtdb? Can the reference database be located outside the install directory (to save disk space by avoiding file duplication if the database is also used for other programs)?

Thanks!

Cheers,
Christiane

**Comment by vcepeda** [comment]
Hi @chassenr,  It's not possible to use a different database in the current version.  The "refseq" directory doesn't contain the complete archaeal bacterial RefSeq database. It contains the complete and almost complete RefSeq genomes and genes and many additional files that are not part of Refseq, such as the predicted marker genes, clustered marker genes, mash sketches, and taxonomy files.

**Comment by chassenr** [comment]
Hi @vcepeda ,
thanks for the info. I will use the default database ;) What about the file location? Can I save the database outside of the install directory? On our server, the location for programs is not big enough for the database as we usually have a separate directory for databases. I would like to avoid installing the program somewhere else to maintain a clean file structure. But this is just a question of convenience... Thanks for your feedback.

Cheers,
Christiane

**Comment by vcepeda** [comment]
After running the install directory, I'd suggest to move the refseq directory somewhere else and create a symlink to refseq in the install directory

**Comment by chassenr** [comment]
Thanks @vcepeda that worked perfectly. Closing the issue now.
