### ISSUE TITLE
Datrie

### ISSUE THREAD

**Issue by bhanusakhamuri** [marbl/MetaCompass#4]
I already installed the Datrie using pip install but this error pops and the assembly gets exiting.

python3.7 go_metacompass.py -r ~/Desktop/MGS\ ref/G.Vaginalis/g.vaginalis.fna -P /Volumes/G-DRIVE\ USB-C/Binned_reads/DN00207A_10/DN00297A_host_removed_r1.fastq,/Volumes/G-DRIVE\ USB-C/Binned_reads/DN00207A_10/DN00297A_host_removed_r2.fastq -o example1_output -m 1 -t 4
confirming file containing reference genomes exists..
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
[OK]
checking for dependencies (Bowtie2, Blast, kmermask, Snakemake, etc)
Bowtie2--->[OK]
/Users/bhanuprakashchowdarysakhamuri/miniconda2/bin//blastn
Blast+--->[OK]
/Users/bhanuprakashchowdarysakhamuri/MetaCompass/bin//kmer-mask
kmer-mask--->[OK]
/usr/local/bin/snakemake
Snakemake--->[OK]
Traceback (most recent call last):
  File "/usr/local/bin/snakemake", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'datrie' distribution was not found and is required by snakemake
ERROR: snakemake command failed; exiting..
touch: example1_output/DN00297A_host_removed_r1.0.assembly.out/run.fail: No such file or directory

**Comment by vcepeda** [comment]
Before this, were you able to run the examples on the Readme successfully?

**Comment by bhanusakhamuri** [comment]
No I directly started running them on my sample data.

**Comment by vcepeda** [comment]
Can you run the examples to see if any error pops up?  I have never encountered the error you mentioned before but it could be a dependency issue.

**Comment by bhanusakhamuri** [comment]
I did upgrade by miniconda and tried the example dataset. Works perfectly fine. When I tried with my dataset the snakemake gets exiting returining

"Config entries have to be defined as name=value pairs."
