### ISSUE TITLE
Error in job reference_recruitment while creating output files

### ISSUE THREAD

**Issue by bharat1912** [marbl/MetaCompass#9]
1. Installed metaCompass v 1.3 (github version in conda in py3.5 env)

2. Tested installation using: Reference-guided assembly with known reference genomes (no reference selection). Completed without erros

3. Ran Reference-guided assembly with reference selection with own samples copied to dir tutorial:
(8010015 seqs, length 300)
$python3 go_metacompass.py -P tutorial/CS1BS_ATBW8_GCCAAT_L001_R1.fastq,tutorial/CS1BS_ATBW8_GCCAAT_L001_R2.fastq -l 300 -o CS1BS.output

4. Created error as follows (tried a few things e.g. downgraded snakeman to 3.11) but none worked. Assistance in trouble shooting appreciated
checking for dependencies (Bowtie2, Blast, kmermask, Snakemake, etc)
/home/bharat/opt/anaconda3/envs/py35/bin/snakemake
Snakemake--->[OK]
Bowtie2--->[OK]
/home/bharat/opt/anaconda3/envs/py35/bin/blastn
Blast+--->[OK]
/home/bharat/opt/anaconda3/envs/py35/bin/kmer-mask
kmer-mask--->[OK]
/usr/bin/mash
mash--->[OK]
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	assemble_unmapped
	1	bam_sort
	1	bowtie2_map
	1	build_contigs
	1	create_tsv
	1	fastq2fasta
	1	join_contigs
	1	kmer_mask
	1	merge_reads
	1	pilon_contigs
	1	pilon_map
	1	reference_recruitment
	1	sam_to_bam
	14
Resources before job selection: {'_nodes': 9223372036854775807, '_cores': 1}
Ready jobs (1):
	merge_reads
Selected jobs (1):
	merge_reads
Resources after job selection: {'_nodes': 9223372036854775806, '_cores': 0}

---merge fastq reads
Reason: Missing output files: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq

Releasing 1 _nodes (now 9223372036854775807).
Releasing 1 _cores (now 1).
Finished job 10.
1 of 14 steps (7%) done
Resources before job selection: {'_nodes': 9223372036854775807, '_cores': 1}
Ready jobs (1):
	kmer_mask
Selected jobs (1):
	kmer_mask
Resources after job selection: {'_nodes': 9223372036854775806, '_cores': 0}

---kmer-mask fastq
Reason: Missing output files: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.marker.match.1.fastq; Input files updated by another job: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq

Releasing 1 _nodes (now 9223372036854775807).
Releasing 1 _cores (now 1).
Finished job 13.
2 of 14 steps (14%) done
Resources before job selection: {'_nodes': 9223372036854775807, '_cores': 1}
Ready jobs (1):
	fastq2fasta
Selected jobs (1):
	fastq2fasta
Resources after job selection: {'_nodes': 9223372036854775806, '_cores': 0}

---Converting fastq to fasta.
Reason: Missing output files: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.fasta; Input files updated by another job: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.marker.match.1.fastq

Releasing 1 _nodes (now 9223372036854775807).
Releasing 1 _cores (now 1).
Finished job 11.
3 of 14 steps (21%) done
Resources before job selection: {'_nodes': 9223372036854775807, '_cores': 1}
Ready jobs (1):
	reference_recruitment
Selected jobs (1):
	reference_recruitment
Resources after job selection: {'_nodes': 9223372036854775806, '_cores': 0}

---reference recruitment.
Reason: Missing output files: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/mc.refseq.fna; Input files updated by another job: CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq, CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.fasta

Full Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 848, in run_wrapper
    version, rule, conda_env)
  File "/home/bharat/opt/anaconda3/envs/py35/MetaCompass/snakemake/metacompass.iter0.paired.py", line 168, in __rule_reference_recruitment
    sam=rules.pilon_map.output.sam
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/site-packages/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir -p CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/py35/MetaCompass/bin/select_references.py tax CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 1 2  1>> CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1

Error in job reference_recruitment while creating output files CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/mc.refseq.ids, CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out, CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/mc.refseq.fna.
Full Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 848, in run_wrapper
    version, rule, conda_env)
  File "/home/bharat/opt/anaconda3/envs/py35/MetaCompass/snakemake/metacompass.iter0.paired.py", line 168, in __rule_reference_recruitment
    sam=rules.pilon_map.output.sam
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/site-packages/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir -p CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/py35/MetaCompass/bin/select_references.py tax CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 1 2  1>> CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 300, in _callback
    raise ex
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 862, in run_wrapper
    show_traceback=True))
snakemake.exceptions.RuleException: CalledProcessError in line 82 of /home/bharat/opt/anaconda3/envs/py35/MetaCompass/snakemake/metacompass.iter0.paired.py:
Command 'mkdir -p CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/py35/MetaCompass/bin/select_references.py tax CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 1 2  1>> CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1
  File "/home/bharat/opt/anaconda3/envs/py35/MetaCompass/snakemake/metacompass.iter0.paired.py", line 82, in __rule_reference_recruitment

RuleException:
CalledProcessError in line 82 of /home/bharat/opt/anaconda3/envs/py35/MetaCompass/snakemake/metacompass.iter0.paired.py:
Command 'mkdir -p CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/py35/MetaCompass/bin/select_references.py tax CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 1 2  1>> CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1
  File "/home/bharat/opt/anaconda3/envs/py35/MetaCompass/snakemake/metacompass.iter0.paired.py", line 82, in __rule_reference_recruitment
  File "/home/bharat/opt/anaconda3/envs/py35/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job reference_recruitment since they might be corrupted:
CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out
Releasing 1 _nodes (now 9223372036854775807).
Releasing 1 _cores (now 1).
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
unlocking
removing lock
removing lock
removed all locks
ERROR: snakemake command failed; exiting..
touch: cannot touch 'CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/run.fail': No such file or directory

**Comment by vcepeda** [comment]
Please share your CS1BS.output/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log, the error should be there.

**Comment by bharat1912** [comment]
Thanks for the prompt response. Below is the information from CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log   
File "/home/bharat/opt/anaconda3/envs/py35/MetaCompass/bin/select_references.py", line 282
    else
       ^
SyntaxError: invalid syntax

**Comment by bharat1912** [comment]
Just wandering if the python version will produce this error. 

Here is the list and versions (built using anaconda3)
# NAME:  Anaconda3
# VER:   2019.03
# PLAT:  linux-64

# packages in environment at /home/bharat/opt/anaconda3/envs/metacompass:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                   py36_0  
bcrypt                    3.1.6            py36h7b6447c_0  
blas                      1.0                         mkl  
blast                     2.9.0           pl526h979a64d_3    bioconda
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_0  
cffi                      1.12.3           py36h2e261b9_0  
chardet                   3.0.4                    py36_1  
cryptography              2.7              py36h1ba5d50_0  
curl                      7.65.2               hbc83047_0  
docutils                  0.14                     py36_0  
dropbox                   9.3.0                    py36_0  
entrez-direct             11.0                    pl526_0    bioconda
expat                     2.2.6                he6710b0_0  
filechunkio               1.6                      py36_0    bioconda
ftputil                   3.2                      py36_0    bioconda
idna                      2.8                      py36_0  
intel-openmp              2019.4                      243  
krb5                      1.16.1               h173b8e3_7  
libcurl                   7.65.2               h20c2e04_0  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
megahit                   1.2.6                h8b12597_0    bioconda
meryl                     2013                          0    bioconda
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4           py36h7e9f1db_0  
numpy-base                1.16.4           py36hde5b4d6_0  
openjdk                   8.0.152              h46b5887_1  
openssl                   1.1.1c               h7b6447c_1  
pandas                    0.24.2           py36he6710b0_0  
paramiko                  2.4.2                    py36_0  
pcre                      8.43                 he6710b0_0  
perl                      5.26.2               h14c3975_0  
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.086           pl526hf484d3e_0    bioconda
perl-compress-raw-zlib    2.086           pl526h6bb024c_1    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.086           pl526hf484d3e_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.50            pl526h14c3975_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pilon                     1.23                          0    bioconda
pip                       19.1.1                   py36_0  
psutil                    5.6.3            py36h7b6447c_0  
pyasn1                    0.4.5                      py_0  
pycparser                 2.19                     py36_0  
pynacl                    1.3.0            py36h7b6447c_0  
pyopenssl                 19.0.0                   py36_0  
pysftp                    0.2.9                    py36_0    bioconda
pysocks                   1.7.0                    py36_0  
python                    3.6.8                h0371630_0  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0  
pyyaml                    5.1.1            py36h7b6447c_0  
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py36_0  
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.1                   py36_0  
six                       1.12.0                   py36_0  
snakemake                 3.13.3                   py36_0    bioconda
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
urllib3                   1.24.2                   py36_0  
wheel                     0.33.4                   py36_0  
wrapt                     1.11.2           py36h7b6447c_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  

-----------------------------------------------------------------------------------
installed using active conda environment with metacompass from github 
# MetaCompass v1.3
Last updated: April 6th, 2019

**Comment by vcepeda** [comment]
I updated the code. Thanks!

**Comment by bharat1912** [comment]
Thank you for updating the code.

1. Updated $~/opt/anaconda3/envs/metacompass/MetaCompass$ git pull https://github.com/marbl/MetaCompass.git
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/marbl/MetaCompass
 * branch            HEAD       -> FETCH_HEAD
Updating 3d187c6..7380e5e
Fast-forward
 bin/select_references.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)


2. Ran the pipeline again but failed with a different error
(metacompass) bharat@bharat-T3500:~/opt/anaconda3/envs/metacompass/MetaCompass$ python3 go_metacompass.py -P tutorial/CS1BS_ATBW8_GCCAAT_L001_R1.fastq,tutorial/CS1BS_ATBW8_GCCAAT_L001_R2.fastq -l 300 -o CS1BS.output_new -m 1 -t 4
checking for dependencies (Bowtie2, Blast, kmermask, Snakemake, etc)
/home/bharat/opt/anaconda3/envs/metacompass/bin/snakemake
Snakemake--->[OK]
Bowtie2--->[OK]
/home/bharat/opt/anaconda3/envs/metacompass/bin/blastn
Blast+--->[OK]
/home/bharat/opt/anaconda3/envs/metacompass/bin/kmer-mask
kmer-mask--->[OK]
/usr/bin/mash
mash--->[OK]
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	assemble_unmapped
	1	bam_sort
	1	bowtie2_map
	1	build_contigs
	1	create_tsv
	1	fastq2fasta
	1	join_contigs
	1	kmer_mask
	1	merge_reads
	1	pilon_contigs
	1	pilon_map
	1	reference_recruitment
	1	sam_to_bam
	14
Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (1):
	merge_reads
Selected jobs (1):
	merge_reads
Resources after job selection: {'_cores': 3, '_nodes': 9223372036854775806}

Job 11: ---merge fastq reads
Reason: Missing output files: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq

Releasing 1 _cores (now 4).
Releasing 1 _nodes (now 9223372036854775807).
Finished job 11.
1 of 14 steps (7%) done
Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (1):
	kmer_mask
Selected jobs (1):
	kmer_mask
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

Job 13: ---kmer-mask fastq
Reason: Missing output files: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.marker.match.1.fastq; Input files updated by another job: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq

Releasing 4 _cores (now 4).
Releasing 1 _nodes (now 9223372036854775807).
Finished job 13.
2 of 14 steps (14%) done
Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (1):
	fastq2fasta
Selected jobs (1):
	fastq2fasta
Resources after job selection: {'_cores': 3, '_nodes': 9223372036854775806}

Job 10: ---Converting fastq to fasta.
Reason: Missing output files: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.fasta; Input files updated by another job: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.marker.match.1.fastq

Releasing 1 _cores (now 4).
Releasing 1 _nodes (now 9223372036854775807).
Finished job 10.
3 of 14 steps (21%) done
Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (1):
	reference_recruitment
Selected jobs (1):
	reference_recruitment
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

Job 6: ---reference recruitment.
Reason: Missing output files: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/mc.refseq.fna; Input files updated by another job: CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.fasta, CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq

Full Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 923, in run_wrapper
    log, version, rule, conda_env, None)
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 170, in __rule_reference_recruitment
    bam = "%s.bam"%(rules.pilon_map.output.sam)
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/shell.py", line 88, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir -p CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/bin/select_references.py tax CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 4 2  1>> CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1.

Error in job reference_recruitment while creating output files CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out, CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/mc.refseq.fna, CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/mc.refseq.ids.
Full Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 923, in run_wrapper
    log, version, rule, conda_env, None)
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 170, in __rule_reference_recruitment
    bam = "%s.bam"%(rules.pilon_map.output.sam)
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/shell.py", line 88, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir -p CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/bin/select_references.py tax CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 4 2  1>> CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 326, in _callback
    raise ex
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 935, in run_wrapper
    show_traceback=True))
snakemake.exceptions.RuleException: CalledProcessError in line 82 of /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py:
Command 'mkdir -p CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/bin/select_references.py tax CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 4 2  1>> CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1.
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 82, in __rule_reference_recruitment

RuleException:
CalledProcessError in line 82 of /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py:
Command 'mkdir -p CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out; python3 /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/bin/select_references.py tax CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.fasta CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.merged.fq CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out 4 2  1>> CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log 2>&1' returned non-zero exit status 1.
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 82, in __rule_reference_recruitment
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job reference_recruitment since they might be corrupted:
CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out
Releasing 4 _cores (now 4).
Releasing 1 _nodes (now 9223372036854775807).
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
unlocking
removing lock
removing lock
removed all locks
ERROR: snakemake command failed; exiting..
touch: cannot touch 'CS1BS.output_new/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/run.fail': No such file or directory


3. The error is reported below from the CS1BS_ATBW8_GCCAAT_L001_R1.0.reference_recruitement.log is given below:
Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/bin/select_references.py", line 432, in <module>
    main() 
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/bin/select_references.py", line 281, in main
    cutoff = sys.argv[7]
IndexError: list index out of range

**Comment by vcepeda** [comment]
Now should be fixed. Please try again!
